### ISSUE TITLE
总是会提示不被信任的应用然后 Chrome 禁止启用怎么办？

### ISSUE THREAD

**Issue by RitterHou** [unclehking/baiduAdfinisher#2]
因为不是商店中的应用，Chrome 总是会禁止启用，没法使用啊

**Comment by unclehking** [comment]
chrome稳定版禁用非商店上架的扩展，建议你使用开发版，更好用。个人感觉 @RitterHou

**Comment by RitterHou** [comment]
请问为什么我下载了开发版的 Chrome，可是还是不能启用？@unclehking 
![qq 20160819130004](https://cloud.githubusercontent.com/assets/11351442/17799378/db1abc0c-660c-11e6-9c89-80794f9bbbd5.png)

**Comment by unclehking** [comment]
先卸载了再安装开发版，不要覆盖安装

**Comment by unclehking** [comment]
先卸载了再安装开发版，不要覆盖安装 @RitterHou
